name: Compile ESP32 bin
'on':
  - push
  - pull_request
jobs:
  build-esp32:
    strategy:
      matrix:
        arduino-platform:
          - 'esp32:esp32'
        include:
          - arduino-platform: 'esp32:esp32'
            fqbn: 'esp32:esp32:esp32'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: >
          arduino-cli --additional-urls
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
          core update-index

          arduino-cli --additional-urls
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
          core install arduino:samd

          arduino-cli --additional-urls
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
          core install esp32:esp32

          arduino-cli core update-index

          arduino-cli core install esp32:esp32
      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32:PSRAM=enabled,PartitionScheme=min_spiffs,CPUFreq=240 ./ESP32/main/main.ino   --libraries ./ESP32/libraries/ --clean
          #arduino-cli compile --fqbn esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=huge_app,CPUFreq=80  ./ESP32/main/main.ino --libraries ./ESP32/libraries/ --export-binaries
          dir ./ESP32/build/
          #IF EXIST ./ESP32/build/main.ino.elf DEL /F ./ESP32/build/main.ino.elf
          #IF EXIST ./ESP32/build/main.ino.map DEL /F ./ESP32/build/main.ino.map
          #IF EXIST ./ESP32/build/main.ino.partitions.bin DEL /F ./ESP32/build/main.ino.partitions.bin
          #IF EXIST ./ESP32/build/main.ino.bootloader.bin           DEL /F ./ESP32/build/main.ino.bootloader.bin          
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: Upload-BIN
          path: ./ESP32/build
      
      - name: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Updating Binaries for Firmware

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: binaries
          create_banch: true

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: '*.bin'

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .

          # Optional commit user and author settings
          commit_user_name: "github-actions[bot]"
          commit_user_email:  "github-actions[bot]@users.noreply.github.com"

          # Optional. Option used by `git-status` to determine if the repository is 
          # dirty. See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'

          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          add_options: '-u'

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          push_options: '--force'

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true    

          # Optional. Skip internal call to `git checkout`
          skip_checkout: true

          # Optional. Prevents the shell from expanding filenames. 
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
   
