name: Compile ESP32 bin

on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  build-esp32:
    strategy:
      matrix:
        arduino-platform:
          - 'esp32:esp32'
        include:
          - arduino-platform: 'esp32:esp32'
            fqbn: 'esp32:esp32:esp32'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: >
          arduino-cli --additional-urls
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
          core update-index

          arduino-cli --additional-urls
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
          core install arduino:samd

          arduino-cli --additional-urls
          https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
          core install esp32:esp32

          arduino-cli core update-index

          arduino-cli core install esp32:esp32
      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=huge_app,CPUFreq=240,FlashMode=dio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,LoopCore=1,EventsCore=1,DebugLevel=none ./ESP32/main/main.ino   --libraries ./ESP32/libraries/ --clean --output-dir=./ESP32/build
          dir ./ESP32/build/
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
      - name: create ZIP
        uses: vimtor/action-zip@v1
        with:
          files: ./ESP32/build/
          dest: binaries.zip
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: binaries.zip
          asset_name: binaries.zip
          asset_content_type: application/zip
